[workspace]
members = [
    "trading-common",
    "trading-core",
    "data-manager",
    "src-tauri",
    "integration-tests"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
license = "MIT"
authors = ["Harrison"]

[workspace.dependencies]
dbn = "0.47"